============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.4.0, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /workspaces/dihya.io
configfile: pytest.ini
plugins: anyio-4.9.0, mock-3.14.1, asyncio-1.0.0, cov-6.1.1
asyncio: mode=strict, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_ ERROR collecting backend/components/metiers/threed/tests_centralises/utils/exporter/core/exporter_core_advanced.test.py _
ImportError while importing test module '/workspaces/dihya.io/backend/components/metiers/threed/tests_centralises/utils/exporter/core/exporter_core_advanced.test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'threed.tests_centralises.utils.exporter.core.exporter_core_advanced'
=========================== short test summary info ============================
ERROR backend/components/metiers/threed/tests_centralises/utils/exporter/core/exporter_core_advanced.test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.37s ==========================
