============================= test session starts ==============================
platform linux -- Python 3.12.1, pytest-8.4.0, pluggy-1.6.0 -- /usr/local/python/3.12.1/bin/python3
cachedir: .pytest_cache
django: version: 5.2.1, settings: backend.django.settings (from ini)
rootdir: /workspaces/dihya.io
configfile: pytest.ini
plugins: anyio-4.9.0, django-4.11.1
collecting ... collected 17 items / 1 error

==================================== ERRORS ====================================
_ ERROR collecting backend/components/metiers/threed/tests/samples/sample_test.py _
ImportError while importing test module '/workspaces/dihya.io/backend/components/metiers/threed/tests/samples/sample_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/python/3.12.1/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend/components/metiers/threed/tests/samples/__init__.py:3: in <module>
    from .sample_test import *
backend/components/metiers/threed/tests/samples/sample_test.py:3: in <module>
    from ...services.core.api.api_service import ApiService
backend/components/metiers/threed/services/core/__init__.py:2: in <module>
    from .service_threed import *
E   ModuleNotFoundError: No module named 'threed.services.core.service_threed'
=========================== short test summary info ============================
ERROR backend/components/metiers/threed/tests/samples/sample_test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.52s ===============================
